### ISSUE TITLE
Vite documentation

### ISSUE THREAD

**Issue by Johann-Goncalves-Pereira** [arowM/elm-css-modules-helper#1]
I would love to use this, but I'm using Vite instead of webpack. [Here is an Elm + Vite project exempla](https://github.com/Johann-Goncalves-Pereira/Revex).

**Comment by arowM** [comment]
Thanks for your interest in this repository, but I recommend you not to use this module.
Check the [last section of README](https://github.com/arowM/elm-css-modules-helper#wait-do-you-realy-need-this-library), and try to handle CSS module with vanilla Elm. 🌱
